[Pallet-Manta-Pay] #37 - Configure weights in the manta pay pallet
Manta-Network/pallet-manta-dap pull request #38
Opened 2021-05-18 13:32 UTC by ghzlatarev

closes #37 

* Adds the auto-generated weights.rs file, from the benchmark process.
* Integrates each extrinsic's weight function.

2021-05-18 13:51 UTC, ghzlatarev commented on src/weights.rs
> +// GNU General Public License for more details.
I copy pasted this from other files in our repo, because it wasn't passing 
With the original substrate text it wasn't passing cargo fmt

2021-05-18 13:52 UTC, ghzlatarev commented on Cargo.toml
> +	"frame-benchmarking",
From testing we don't seem to need the following:
```
"frame-support/runtime-benchmarks",
"frame-system/runtime-benchmarks",
```
but I just have a feeling we gotta add them ...

2021-05-18 13:55 UTC, zhenfeizhang commented on src/weights.rs
> +// GNU General Public License for more details.
yeah... now having manta license header is mandatory. This is the cfg that enabled this feature
https://github.com/Manta-Network/pallet-manta-asset/blob/81f0f125eab76321d6826b68d6ce88c735f22d2b/.rustfmt.toml#L3

2021-05-18 13:58 UTC, zhenfeizhang approved these changes
LGTM. Thanks!

2021-05-18 13:59 UTC, ghzlatarev commented on src/weights.rs
> +// GNU General Public License for more details.
Nice, very cool.

2021-05-18 14:01 UTC, zhenfeizhang commented on Cargo.toml
> +	"frame-benchmarking",
I don't think we need them for the `pallet-manta-pay`. Prob need them within `manta`.
We should leave them out until rust complains....

2021-05-18 14:02 UTC, ghzlatarev commented
By the way, I tested this by running a couple of nodes locally, and using the extrinsics through the Polkadot.js app. Then in the block description with each extrinsic there is some data including the weight. The weight can also be checked in the browser console.
Maybe someone else can also test it along with https://github.com/Manta-Network/Manta/pull/48

2021-05-18 17:09 UTC, stechu requested changes
Can you add your machine configuration in `Readme.md` ? It is good to have a reference point if we want to change it in the future.

2021-05-18 17:13 UTC, ghzlatarev commented
> Can you add your machine configuration in `Readme.md` ? It is good to have a reference point if we want to change it in the future.

I'm also using AMD Ryzen 9 5900X 12-Core Processor; Ubuntu 20.04; rustc 1.50.0 which is in the Readme.md already. Do you mean add something else ?

2021-05-18 17:18 UTC, ghzlatarev commented
> > Can you add your machine configuration in `Readme.md` ? It is good to have a reference point if we want to change it in the future.
> 
> I'm also using AMD Ryzen 9 5900X 12-Core Processor; Ubuntu 20.04; rustc 1.50.0 which is in the Readme.md already. Do you mean add something else ?

Actually it doesn't even matter . These weight functions assume the worst case scenario for the runtime.

2021-05-18 17:55 UTC, ghzlatarev commented
> > > Can you add your machine configuration in `Readme.md` ? It is good to have a reference point if we want to change it in the future.
> > 
> > 
> > I'm also using AMD Ryzen 9 5900X 12-Core Processor; Ubuntu 20.04; rustc 1.50.0 which is in the Readme.md already. Do you mean add something else ?
> 
> Actually it doesn't even matter . These weight functions assume the worst case scenario for the runtime. They will do a refund of excess weight after the actual execution of the extrinsic.

@stechu @zhenfeizhang 
This is a bit of a guess, but I think it is not even runtime dependent anymore, meaning any other runtime developer can use the weights.rs file we've generated, as it is directly embedded in the pallet-manta-pay repo. Only changes to the pallet code will require us to recreate the weights.rs file.
It seems before every runtime developer had to benchmark each pallet and produce a weight.rs file, which was embedded in their node's repo alongside all other pallets they use.

2021-05-18 20:26 UTC, stechu commented
It turns out the weight generated is *different* for different machine configurations. For example, the weights generated in a MBP 16 with Core-i9  is roughly 2x compared with the weights generated in a desktop machine with Ryzen 5900X. So we should set the weight with respect to a *recommended configuration* with some slackness. A sensible choice of a *recommend configuration* should be roughly equivalent to some cloud instance tier.

2021-05-18 20:47 UTC, zhenfeizhang commented
I think it is sufficient to merge this PR now; and creating a new Issue on updating the `weight.rs` file.

2021-05-19 06:49 UTC, stechu commented
@zhenfeizhang  sounds good to me. @ghzlatarev  can you update the `readme.md` with your current CPU/Mem/Storage information? After that, this PR is good to go.

2021-05-19 07:29 UTC, ghzlatarev commented
> @zhenfeizhang sounds good to me. @ghzlatarev can you update the `readme.md` with your current CPU/Mem/Storage information? After that, this PR is good to go.

Will do.

2021-05-19 07:34 UTC, ghzlatarev commented
> It turns out the weight generated is _different_ for different machine configurations. For example, the weights generated in a MBP 16 with Core-i9 is roughly 2x compared with the weights generated in a desktop machine with Ryzen 5900X. So we should set the weight with respect to a _recommended configuration_ with some slackness. A sensible choice of a _recommend configuration_ should be roughly equivalent to some cloud instance tier.

Yes and I logged the other important piece of our discussion about benchmarking other pallets in our runtime and overriding their weight functions. https://github.com/Manta-Network/Manta/issues/49

2021-05-19 08:15 UTC, ghzlatarev commented
> @zhenfeizhang sounds good to me. @ghzlatarev can you update the `readme.md` with your current CPU/Mem/Storage information? After that, this PR is good to go.

Included the storage and memory. 
The runtime execution engine is evident from the command.
Should I include drivers information?

2021-05-19 11:21 UTC, zhenfeizhang commented
> > @zhenfeizhang sounds good to me. @ghzlatarev can you update the `readme.md` with your current CPU/Mem/Storage information? After that, this PR is good to go.
> 
> Included the storage and memory.
> The runtime execution engine is evident from the command.
> Should I include drivers information?

I don't think drivers are necessary. It should be sufficient for now.

2021-05-19 11:25 UTC, ghzlatarev commented
> > > @zhenfeizhang sounds good to me. @ghzlatarev can you update the `readme.md` with your current CPU/Mem/Storage information? After that, this PR is good to go.
> > 
> > 
> > Included the storage and memory.
> > The runtime execution engine is evident from the command.
> > Should I include drivers information?
> 
> I don't think drivers are necessary. It should be sufficient for now.

Can you merge this, or should I integrate the new weights.rs file from the Cloud instance benchmarking in this PR?

2021-05-19 11:27 UTC, zhenfeizhang commented
@stechu requested some changes... I think he needs to approve this. I can't merge

2021-05-19 11:30 UTC, ghzlatarev commented
> @stechu requested some changes... I think he needs to approve this. I can't merge

Ok i'll push here and stash the old weights.rs from the AMD Ryzen environment somewhere for reference.

2021-05-19 15:47 UTC, stechu approved these changes
LGTM.

2021-05-19 15:47 UTC, merged