[Manta] Refactor
Manta-Network/pallet-manta-dap pull request #39
Opened 2021-05-18 15:51 UTC by zhenfeizhang

* moving out the crypto algorithms to manta-crypto
* moving out the asset definitions to pallet-manta-pay
* better circuit abstraction

2021-05-18 19:23 UTC, zhenfeizhang commented
Will need to add more comments to improve the readability of the code

2021-05-19 16:37 UTC, ghzlatarev commented on Cargo.toml
> +pallet-manta-asset = { branch = "master", git = "https://github.com/Manta-Network/pallet-manta-asset" }
Nice.

2021-05-19 18:04 UTC, ghzlatarev commented on src/payload/mod.rs
> +///       reclaim intrinsic.
reclaim extrinsic*

2021-05-19 19:04 UTC, zhenfeizhang commented on src/payload/mod.rs
> +///       reclaim intrinsic.
thanks. Fixed/

2021-05-19 20:10 UTC, stechu requested changes

2021-05-19 20:10 UTC, stechu commented on src/zkp/gadget.rs
> +pub(crate) fn merkle_membership_circuit_proof(
should this be part of `manta-crypto`?

2021-05-19 20:10 UTC, stechu commented on src/zkp/keys.rs
> +pub fn write_zkp_keys() {
inline comments/doc of the function?

2021-05-19 20:10 UTC, stechu commented on src/zkp/keys.rs
> +fn manta_transfer_zkp_key_gen(
inline comments/doc of the function?

2021-05-19 20:10 UTC, stechu commented on src/zkp/keys.rs
> +fn manta_reclaim_zkp_key_gen(
inline comments/doc of the function?

2021-05-19 20:12 UTC, zhenfeizhang commented on src/zkp/gadget.rs
> +pub(crate) fn merkle_membership_circuit_proof(
no. its manta-pay specific circuit. it will create a cyclic dependency if moved.

2021-05-19 20:17 UTC, zhenfeizhang commented on src/zkp/keys.rs
> +pub fn write_zkp_keys() {
fixed

2021-05-19 20:17 UTC, zhenfeizhang commented on src/zkp/keys.rs
> +fn manta_reclaim_zkp_key_gen(
fixed

2021-05-19 20:17 UTC, zhenfeizhang commented on src/zkp/keys.rs
> +fn manta_transfer_zkp_key_gen(
fixed

2021-05-19 20:26 UTC, ghzlatarev commented on src/test/frame.rs
> +// use x25519_dalek::{PublicKey, StaticSecret};
Forgotten commented out code.

2021-05-20 01:16 UTC, zhenfeizhang commented
let's get #40 merged before merging this one

2021-05-20 07:13 UTC, ghzlatarev approved these changes

2021-05-20 07:48 UTC, stechu approved these changes

2021-05-20 07:49 UTC, merged