[manta] [ready tp merge] update with manta-types
Manta-Network/pallet-manta-dap pull request #61
Opened 2021-06-02 21:42 UTC by zhenfeizhang

this should solve all the broken dependencies

2021-06-02 21:53 UTC, ghzlatarev approved these changes

2021-06-02 23:19 UTC, stechu requested changes
LGTM in general. Please fix the conflicts and it should be good to go.

2021-06-02 23:19 UTC, stechu commented on Cargo.toml
> +manta-data = { branch = "manta", git = "https://github.com/Manta-Network/manta-types", default-features = false }
why use a different name here?

2021-06-04 20:21 UTC, zhenfeizhang commented
force merging this: the CI has passed. and a couple of other branches need this PR.

2021-06-04 20:21 UTC, merged