Storage refactor
Manta-Network/pallet-manta-dap pull request #91
Opened 2021-08-14 02:45 UTC by stechu

This is part of storage refactor with:
https://github.com/Manta-Network/Manta/pull/152

The major goal is to remove all the `O(N)` operations with `O(1)` (or at least `O(Log N)` ) operations.

2021-10-01 06:24 UTC, bhgomes commented on src/lib.rs
> +				if LedgerShardRoots::<T>::take(sender.shard_index) != sender.root {
What's the difference between `take` and `get`? Usually when I see `take` I assume that the inner value is returned and then set to a default value (see `core::mem::take` in the standard library for example).

2021-10-01 06:25 UTC, bhgomes commented on src/lib.rs
> -				})?;
Why aren't we checking this anymore?

2021-10-01 06:28 UTC, bhgomes commented on src/lib.rs
>  			let origin_account = origin.clone();
This `clone` isn't necessary.

2021-10-01 06:30 UTC, bhgomes commented on src/lib.rs
> +			}
What about the ledger shard root check, like in `PrivateTransfer`?

2021-10-01 06:32 UTC, bhgomes commented on src/lib.rs
> +		}
You can replace this with `UTXOSet::<T>::try_get(utxo).is_ok()`.

2021-10-01 06:35 UTC, bhgomes approved these changes
See comments. 👍

2021-10-01 06:41 UTC, stechu commented on src/lib.rs
> +				if LedgerShardRoots::<T>::take(sender.shard_index) != sender.root {
Thanks for spotting the issue. I misunderstood the semantics of `take`. It should indeed be `get` here.

2021-10-01 06:42 UTC, stechu commented on src/lib.rs
> +				if LedgerShardRoots::<T>::take(sender.shard_index) != sender.root {
The difference is that `take` removes the values afterwards.

2021-10-01 06:48 UTC, stechu commented on src/lib.rs
>  			let origin_account = origin.clone();
indeed.

2021-10-01 06:48 UTC, stechu commented on src/lib.rs
> +			}
good catch. will fix.

2021-10-08 08:27 UTC, ghzlatarev commented on src/benchmarking.rs
> +// TODO: move all these precomputed coins to build script
This todo doesn't seem to be relevant anymore.

2021-10-08 10:24 UTC, ghzlatarev commented on src/lib.rs
> +		/// FIXME: this part need to move out of pallet-manta-pay
Can we log all the fixmes and todos that won't be completed in this PR ?

2021-10-08 16:17 UTC, stechu commented on src/benchmarking.rs
> +// TODO: move all these precomputed coins to build script
yes, it still is ...

2021-10-08 23:53 UTC, stechu commented on src/lib.rs
> +		/// FIXME: this part need to move out of pallet-manta-pay
sure!

2021-10-10 15:01 UTC, Dengjianping reviewed
Safe math.

2021-10-10 15:01 UTC, Dengjianping commented on src/lib.rs
> -				|balance| *balance = old_pool_balance + mint_data.amount
Can we just replace +/-/* these math operations with `saturating_add`/`saturating_sub`/`saturating_mul`? They're more safe.

2021-10-10 15:57 UTC, bhgomes commented on src/lib.rs
> -				|balance| *balance = old_pool_balance + mint_data.amount
The overflow checks are already there. Also, saturating operations would be incorrect here, the only kind that would make sense are `checked_*`.

2021-10-14 08:51 UTC, bhgomes commented on README.md
> +cargo run --release --bin precompute_coins --features=precompute-coins > /src/precomputed_coins.rs
Shouldn't it be `src/precomputed_coins.rs`?

2021-10-14 08:52 UTC, bhgomes requested changes
See comment.

2021-10-17 15:34 UTC, Dengjianping commented on src/lib.rs
> +			Self::deposit_event(Event::Issued(asset_id, origin.clone(), total));
Remove unnecessary clone.

2021-10-17 15:34 UTC, Dengjianping commented on src/lib.rs
> +			Balances::<T>::mutate(origin.clone(), asset_id, |balance| *balance -= amount);
Remove unnecessary clone from line 292 and 293. Use reference directly.

2021-10-17 15:34 UTC, Dengjianping commented on src/lib.rs
>  			let origin_account = origin.clone();
Remove unnecessary clone.

2021-10-17 15:34 UTC, Dengjianping commented on src/lib.rs
> +				Err("duplicate utxo").map_err(|_| MantaError::LedgerUpdateFail)?;
Perhaps this is better? `duplicate utxo` is unused.
```rust
log::error!(target: "manta-pay", "duplicate utxo");
Err(MantaError::LedgerUpdateFail)?;
```

2021-10-17 15:34 UTC, Dengjianping commented
And make clippy happy.

2021-10-17 15:40 UTC, Dengjianping commented on src/lib.rs
> +		UTXOSet::<T>::try_get(utxo).is_ok()
How about `contains_key`? `try_get` is kind of expensive, it will return the value of `T`.
```rust
UTXOSet::<T>::contains_key(utxo)
```

2021-10-18 23:48 UTC, stechu commented
@Dengjianping @bhgomes  let me know whether your comments have been addressed.

2021-10-18 23:59 UTC, bhgomes approved these changes
Looks great! 🚀

2021-10-19 02:11 UTC, Dengjianping commented on src/lib.rs
> +			Balances::<T>::mutate(origin.clone(), asset_id, |balance| *balance -= amount);
`origin.clone()` -> `&origin`, both line 292 and 293. @stechu

2021-10-19 02:15 UTC, Dengjianping commented
Perhaps you need to re-benchmark it once the code doesn't change anymore.

2021-10-19 03:15 UTC, stechu commented
> Perhaps you need to re-benchmark it once the code doesn't change anymore.

Yeah, I would also like to do a benchmark on a non-clean state. That would be a separate PR.

2021-10-19 07:28 UTC, Dengjianping approved these changes
LGTM!

2021-10-20 12:17 UTC, ghzlatarev commented on src/benchmark/mod.rs
> +			Event::Transferred(TEST_ASSET, caller.clone(), recipient.clone(), transfer_amount).into()
Unnecessary clone for `caller`.

2021-10-20 12:17 UTC, ghzlatarev commented on src/benchmark/mod.rs
> +		assert_last_event::<T>(Event::Reclaimed(TEST_ASSET, caller.clone(), 79_515).into());
Unnecessary clone for `caller`.

2021-10-20 12:18 UTC, ghzlatarev commented on src/bin/precompute_coins.rs
> +	shard.push(utxo.clone());
Unnecessary clone.

2021-10-20 12:21 UTC, ghzlatarev commented on src/test/frame.rs
> +	shard.push(utxo.clone());
Can dereference instead of clone.

2021-10-20 12:23 UTC, ghzlatarev commented on src/test/frame.rs
> +			into_array_unchecked(receivers.clone()),
Unnecessary clone.

2021-10-20 12:23 UTC, ghzlatarev commented on src/test/frame.rs
> +			into_array_unchecked(receivers.clone()),
Unnecessary clone.

2021-10-20 12:24 UTC, ghzlatarev commented on src/test/frame.rs
> +			receiver.clone(),
Unnecessary clone.

2021-10-20 12:24 UTC, ghzlatarev commented on src/test/frame.rs
> +			receiver.clone(),
Unnecessary clone.

2021-10-20 13:07 UTC, ghzlatarev commented on src/lib.rs
> +			}
These checks are kind of duplicated in `reclaim`.
We can have a function like:
```
fn check_double_spend_and_verify_merkle_root(
		senders: &[SenderData; 2],
		error_string: &str,
	) -> DispatchResultWithPostInfo {
		for sender in senders {
			if VoidNumbers::<T>::contains_key(sender.void_number) {
				Err("coin exists").map_err::<DispatchError, _>(|e| {
					log::error!(target: "manta-pay", "failed to {} the private asset with error: {:?}", error_string, e);
					Error::<T>::MantaCoinSpent.into()
				})?;
			}
			if LedgerShardRoots::<T>::get(sender.shard_index) != sender.root {
				Err("invalid root").map_err::<DispatchError, _>(|e| {
					log::error!(target: "manta-pay", "failed to {} the private asset with error: {:?}", error_string, e);
					Error::<T>::InvalidLedgerState.into()
				})?;
			}
		}

		Ok(().into())
	}
```

2021-10-20 13:08 UTC, ghzlatarev commented on src/lib.rs
> +			}
`Pallet::<T>::check_double_spend_and_verify_merkle_root(&senders, "transfer")?;`

2021-10-20 14:23 UTC, ghzlatarev commented on src/lib.rs
> +					// TODO: emit warning if ledger is full
Is this logged, or can we implement it now ?

2021-10-21 01:59 UTC, stechu commented on src/lib.rs
> +					// TODO: emit warning if ledger is full
will log it, thanks for catching this.

2021-10-21 02:07 UTC, stechu commented on src/lib.rs
> +			}
I get your idea. but the utility function's return type need to be `DispatchResult` instead of `DispathResultWithPostInfo`.

2021-10-21 10:11 UTC, ghzlatarev approved these changes

2021-10-22 05:04 UTC, merged