add testnet assets
Manta-Network/pallet-manta-dap pull request #99
Opened 2021-11-09 01:34 UTC by stechu

- [ ] move asset init to genesis build time
- [ ] update tests

2021-11-09 15:44 UTC, bhgomes commented on src/lib.rs
> -			);
How do we want to handle this case now that the initialization is handled at genesis? Just assume a correct configuration?

2021-11-09 15:47 UTC, bhgomes requested changes

2021-11-09 15:47 UTC, bhgomes commented on src/lib.rs
> +	fn init_asset(owner: T::AccountId, asset_id: AssetId, total: AssetBalance) {
`owner` can be passed by reference here. Removes all the clones everywhere else.

2021-11-09 15:47 UTC, bhgomes commented on src/lib.rs
> +			for (asset, supply) in self.assets.clone() {
You can use

```rust
for (asset, supply) in &self.assets {
    Pallet::<T>::init_asset(&self.owner, *asset, *supply);
}
```

to avoid cloning.

2021-11-09 16:25 UTC, bhgomes commented
Also, we should remove the `init_asset` from the "Dispatchable Functions" in the `lib.rs` module docstring.

2021-11-09 18:12 UTC, stechu commented on src/lib.rs
> -			);
Yes, the configuration has to be right, and the asset is fixed at genesis time.

2021-11-10 00:28 UTC, bhgomes approved these changes

2021-11-10 00:50 UTC, merged